---
title: "Reproduced analysis of FARS data"
author: "Ethan Walker"
date: "October 30, 2017"
output: html_document
---

```{r, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)

load("../data/clean_fars.RData")
source("../R/fars_functions.R")
```

#Results
  
```{r}
clean_fars %>%
mutate(year_cat = cut(year, breaks = c(1999, 2002, 2006, 2010),
labels = c("1999-2002", "2003-2006",
"2007-2010"),
include.lowest = TRUE, right = TRUE)) %>%
filter(!is.na(sex)) %>%
group_by(drug_type, sex, year_cat) %>%
summarize(n_non_missing = sum(!is.na(positive_for_drug)),
positive_test = sum(positive_for_drug, na.rm = TRUE),
perc_positive = round(100 * positive_test / n_non_missing, 1)) %>%
select(drug_type, sex, year_cat, perc_positive) %>%
unite(sex_year_cat, sex, year_cat) %>%
spread(sex_year_cat, perc_positive) %>%
knitr::kable(col.names = c("Drug type", "F 1999-2002",
"F 2003-2006", "F 2007-2010",
"M 1999-2002", "M 2003-2006",
"M 2007-2010"))
```


```{r}
drug_list <- c("Alcohol", "Cannabinoid", "Depressant", "Narcotic", "Other", 
               "Stimulant")
drug_trend_tests <- lapply(drug_list, perc_cis)
#drug_trend_tests <- dplyr::bind_rows(drug_trend_tests) %>%
drug_trend_tests <- drug_trend_tests %>% 
  dplyr::mutate(`Drug type` = drug_list) %>%
  dplyr::select(`Drug type`)
drug_trend_tests %>% knitr::kable()
```


```{r}
drug_list <- c("Alcohol", "Nonalcohol", "Narcotic", "Depressant",
               "Stimulant", "Cannabinoid", "Other")
drug_trend_tests_ca <- lapply(drug_list, test_trend_ca)
drug_trend_tests_ca <- dplyr::bind_rows(drug_trend_tests_ca) %>%
  dplyr::mutate(drug = drug_list) %>%
  dplyr::select(drug, Z, p.value)
drug_trend_tests_ca %>% knitr::kable()
```


```{r}
drug_list <- c("Alcohol", "Nonalcohol", "Narcotic", "Depressant",
               "Stimulant", "Cannabinoid", "Other")
drug_trend_tests_log_reg <- lapply(drug_list, test_trend_log_reg)
drug_trend_tests_log_reg <- dplyr::bind_rows(drug_trend_tests_log_reg) %>%
  dplyr::mutate(drug = drug_list) %>%
  dplyr::select(drug, Z, p.value)
drug_trend_tests_log_reg %>% knitr::kable()
```